main:
  logging: "warn"
  destination: ":8080"
  cuda-enable: true

processing:
  pipeline:
    - "ollama.wasm"
    - "style-transfer.wasm"
    - "captions.wasm"

configuration:
  ollama-model: "minicpm-v"
  ollama-prompt: "Describe esta imagen de una manera muy favorable y positiva en 6 palabras."
  caption-line-height: "30"
  caption-size: "0.9"

models:
  download: true

server:
  mcp-enable: false
  mcp-port: ":5001"

